# frozen_string_literal: true

require "prawn"
require "prawn/table"

Prawn::Fonts::AFM.hide_m17n_warning = true

module Reports
  module Pdf
    class BillingDocument
      HONDA_RED = "CC0000"
      HEADER_BG = "1A1A1A"
      MUTED = "666666"
      LINE = "333333"
      BUNDLED_LOGO = Rails.root.join("app/assets/images/honda_logo.png")
      LOGO_CONTENT_TYPES = %w[image/png image/jpeg image/jpg image/gif].freeze
      COPY_LABELS = {
        "original" => "ORIGINAL FOR RECIPIENT",
        "duplicate" => "DUPLICATE FOR TRANSPORTER",
        "triplicate" => "TRIPLICATE FOR SUPPLIER"
      }.freeze
      FOOTER_COPY = {
        "original" => "CLIENT",
        "duplicate" => "TRANSPORTER",
        "triplicate" => "SUPPLIER"
      }.freeze

      def initialize(record, settings: Setting.instance, copy_type: "original")
        @record = record
        @settings = settings
        @copy_type = copy_type.to_s
      end

      def render
        with_logo_file do |logo_path|
          @logo_path = logo_path
          Prawn::Document.new(page_size: "A4", page_layout: :portrait, margin: [ 24, 28, 36, 28 ]) do |pdf|
            render_watermark(pdf)
            render_body(pdf)
            pdf.number_pages "#{@settings.showroom_name}  |  Page <page> of <total>  |  Computer generated",
                             at: [ pdf.bounds.left, -8 ],
                             align: :center,
                             size: 7,
                             color: "888888"
          end.render
        end
      end

      private

      def render_copy_banner(pdf)
        label = copy_labels[@copy_type]
        return if label.blank?

        pdf.text label, size: 9, style: :bold, align: :right, color: HONDA_RED
        pdf.move_down 4
      end

      def copy_labels
        COPY_LABELS
      end

      def footer_copy_label
        FOOTER_COPY[@copy_type]
      end

      def render_watermark(pdf)
        pdf.canvas do
          pdf.transparent(0.05) do
            pdf.fill_color HONDA_RED
            pdf.text_box "AUTHORIZED HONDA DEALER",
                         at: [ 70, 470 ],
                         width: 450,
                         height: 80,
                         size: 28,
                         style: :bold,
                         align: :center,
                         rotate: 32,
                         rotate_around: :center,
                         overflow: :shrink_to_fit
          end
        end
        pdf.fill_color "000000"
      end

      def render_einvoice_block(pdf, record)
        return if record.blank? || record.try(:irn).blank?

        pdf.move_down 4
        pdf.text "e-Invoice (IRN captured from GSP / Honda HiRise — not generated by this app)", size: 8, style: :bold
        pdf.text "IRN: #{record.irn}", size: 7
        pdf.text [
          ("Ack No.: #{record.ack_no}" if record.ack_no.present?),
          ("Ack Date: #{format_date(record.ack_date)}" if record.ack_date.present?)
        ].compact.join("  |  "), size: 7
        pdf.move_down 6
      end

      def render_dealer_header(pdf, document_title, folio: [])
        render_copy_banner(pdf)
        render_letterhead(pdf, folio)
        render_title_bar(pdf, document_title)
      end

      def render_letterhead(pdf, folio)
        dealer_lines = [
          { content: @settings.legal_showroom_name, size: 12, font_style: :bold, text_color: HONDA_RED },
          { content: "Authorized Honda Motorcycle & Scooter Dealer", size: 8, text_color: MUTED },
          ({ content: "Dealer Code: #{@settings.dealer_code}", size: 8 } if @settings.dealer_code.present?),
          { content: @settings.address.to_s, size: 8 },
          ({ content: [ @settings.phone, @settings.email ].compact_blank.join("  |  "), size: 8 } if [ @settings.phone, @settings.email ].compact_blank.any?),
          { content: [
              ("GSTIN: #{@settings.gstin}" if @settings.gstin.present?),
              ("PAN: #{@settings.pan}" if @settings.pan.present?),
              ("State: #{@settings.place_of_supply_label}" if @settings.state.present? || @settings.state_code.present?)
            ].compact.join("  |  "), size: 8, font_style: :bold }
        ].compact

        dealer_text = "<b><color rgb='#{HONDA_RED}'>#{escape_pdf(@settings.legal_showroom_name)}</color></b>\n" \
                      "<color rgb='#{MUTED}'>Authorized Honda Motorcycle &amp; Scooter Dealer</color>\n" \
                      "#{escape_pdf(dealer_lines.drop(2).map { |line| line[:content] }.join("\n"))}"

        pdf.table(
          [ [ logo_cell, { content: dealer_text, inline_format: true }, folio_cell(pdf, folio) ] ],
          width: pdf.bounds.width,
          column_widths: [ 82, pdf.bounds.width - 82 - 168, 168 ],
          cell_style: { borders: [ :top, :bottom, :left, :right ], border_color: LINE, border_width: 0.5, padding: [ 6, 6, 6, 6 ], size: 8, valign: :center }
        ) do
          row(0).columns(0).align = :center
          row(0).columns(2).padding = [ 2, 2, 2, 2 ]
        end
        pdf.move_down 6
      end

      def logo_cell
        if @logo_path.present?
          { image: @logo_path, fit: [ 70, 58 ], position: :center, vposition: :center }
        else
          { content: "H\nHONDA", align: :center, valign: :center, text_color: HONDA_RED, font_style: :bold, size: 11, leading: 2 }
        end
      rescue StandardError
        { content: "H\nHONDA", align: :center, valign: :center, text_color: HONDA_RED, font_style: :bold, size: 11 }
      end

      def folio_cell(pdf, folio)
        if folio.blank?
          return { content: "AUTHORIZED\nHONDA DEALER", align: :center, valign: :center, text_color: HONDA_RED, font_style: :bold, size: 8 }
        end

        rows = folio.map { |label, value| [ label.to_s, value.to_s.presence || "—" ] }
        pdf.make_table(rows, width: 160, cell_style: { size: 7, padding: [ 3, 4, 3, 4 ], borders: [ :bottom ], border_color: "DDDDDD", border_width: 0.4 }) do
          columns(0).font_style = :bold
        end
      end

      def escape_pdf(text)
        text.to_s.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;")
      end

      def render_title_bar(pdf, document_title)
        y = pdf.cursor
        pdf.fill_color HONDA_RED
        pdf.fill_rectangle [ 0, y ], pdf.bounds.width, 20
        pdf.fill_color "FFFFFF"
        pdf.text_box document_title.to_s.upcase,
                     at: [ 4, y - 3 ],
                     width: pdf.bounds.width - 8,
                     height: 16,
                     align: :center,
                     size: 11,
                     style: :bold,
                     overflow: :shrink_to_fit
        pdf.fill_color "000000"
        pdf.move_down 26
      end

      def render_boxed_parties(pdf, supplier_text, recipient_text, supplier_title: "Billed From (Supplier)", recipient_title: "Billed To (Recipient)")
        pdf.table(
          [
            [
              { content: supplier_title, font_style: :bold, background_color: HEADER_BG, text_color: "FFFFFF" },
              { content: recipient_title, font_style: :bold, background_color: HEADER_BG, text_color: "FFFFFF" }
            ],
            [ supplier_text, recipient_text ]
          ],
          width: pdf.bounds.width,
          cell_style: { size: 8, padding: [ 5, 6, 5, 6 ], borders: [ :top, :bottom, :left, :right ], border_color: LINE, border_width: 0.5 }
        )
        pdf.move_down 8
      end

      def render_vehicle_strip(pdf, model:, engine:, serial:)
        pdf.table(
          [
            [
              { content: "MODEL", font_style: :bold, background_color: HEADER_BG, text_color: "FFFFFF", align: :center },
              { content: "ENGINE NUMBER", font_style: :bold, background_color: HEADER_BG, text_color: "FFFFFF", align: :center },
              { content: "SERIAL NUMBER (CHASSIS)", font_style: :bold, background_color: HEADER_BG, text_color: "FFFFFF", align: :center }
            ],
            [
              { content: model.to_s.presence || "—", align: :center, font_style: :bold },
              { content: engine.to_s.presence || "—", align: :center, font_style: :bold },
              { content: serial.to_s.presence || "—", align: :center, font_style: :bold }
            ]
          ],
          width: pdf.bounds.width,
          cell_style: { size: 8, padding: [ 5, 6, 5, 6 ], borders: [ :top, :bottom, :left, :right ], border_color: LINE, border_width: 0.5 }
        )
        pdf.move_down 8
      end

      def render_authorized_signatory(pdf, terms: nil)
        if terms.present?
          pdf.text "Declaration / Terms", size: 9, style: :bold
          pdf.text terms, size: 7, color: MUTED
          pdf.move_down 8
        end

        pdf.text "Certified that the particulars given above are true and correct.", size: 7, color: MUTED
        pdf.move_down 22
        pdf.text "Authorized Signatory", size: 8, align: :right, style: :bold
        pdf.text @settings.legal_showroom_name, size: 7, align: :right, color: MUTED
        pdf.move_down 10
        render_dealer_banner(pdf)
      end

      def render_dealer_banner(pdf)
        copy = footer_copy_label
        pdf.table(
          [ [ "AUTHORIZED HONDA DEALER", copy.presence || "" ] ],
          width: pdf.bounds.width,
          cell_style: {
            size: 8,
            font_style: :bold,
            text_color: "FFFFFF",
            background_color: HONDA_RED,
            padding: [ 5, 8, 5, 8 ],
            borders: []
          }
        ) do
          columns(1).align = :right
        end
      end

      def money(amount)
        format("Rs. %.2f", amount.to_d)
      end

      def format_date(date)
        date.present? ? date.strftime("%d %b %Y") : "-"
      end

      def default_terms
        @settings.billing_terms.presence ||
          "1. Ex-showroom price is GST-inclusive. 2. Insurance and RTO are collected on behalf of the insurer and registering authority. " \
          "3. Subject to showroom jurisdiction. 4. Authorized Honda dealers also punch this sale in Honda HiRise as required by HMSI."
      end

      def with_logo_file
        if @settings.logo.attached? && LOGO_CONTENT_TYPES.include?(@settings.logo.content_type.to_s)
          return @settings.logo.open { |file| yield(file.path) }
        end

        bundled = BUNDLED_LOGO
        return yield(bundled.to_s) if bundled.exist?

        yield(nil)
      rescue StandardError
        bundled = BUNDLED_LOGO
        bundled.exist? ? yield(bundled.to_s) : yield(nil)
      end
    end
  end
end
