# Oracle Always Free — Mumbai Ampere Ubuntu 22.04
# Dummy db/seeds.rb is never run in production.
service: shree_banke_bihari_honda

image: rishubhlodhi121/shree_banke_bihari_honda

servers:
  web:
    - 152.67.9.50

proxy:
  ssl: true
  host: 152-67-9-50.sslip.io

registry:
  username: rishubhlodhi121
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    APP_HOST: 152-67-9-50.sslip.io
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "shree_banke_bihari_honda_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64
  remote: ssh://ubuntu@152.67.9.50

ssh:
  user: ubuntu
